WIP: Telegram Bot: Call the tweepy auth function to the telegram class
Aniketh01/NaWaB pull request #40
Opened 2020-04-25 17:57 UTC by iammarco11

Please check the code and suggest me how to do it. The code is incorrect

2020-04-25 18:01 UTC, Aniketh01 reviewed
Is this changes tested? Is it working for you?

2020-04-25 18:06 UTC, iammarco11 commented
It was tested but was not working. Error was api was undefined.

2020-04-25 18:11 UTC, Aniketh01 requested changes
> It was tested but was not working. Error was api was undefined.

Fix it, please. You need to understand how classes work and how you can import that particular function can be imported to tg bot class. Find similarities in nawab.py. Perhaps you might have to re-write the twitter class definition itself. Keep an open mind :)

Try to read a bit on class and objects in python and how to call those methods and stuff. General OOP concepts would do well too :)

2020-04-25 18:11 UTC, Aniketh01 commented on tg_bot.py
> +        api = Twitter_Bot.nawab_twitter_authenticate()
'nawab_twitter_authenticate()' does the tweepy authentication for you, Why wrapping it up again in a function?

2020-04-25 18:11 UTC, Aniketh01 commented on tg_bot.py
> +        api = tweepy.API(auth)"""
Rather than commenting, remove it off!

2020-04-25 18:11 UTC, Aniketh01 commented on tg_bot.py
> +            self.api.retweet(data)
Does this work for you?? I doubt it.

2020-04-26 06:56 UTC, iammarco11 commented on tg_bot.py
> +            self.api.retweet(data)
it works

2020-04-26 07:12 UTC, Aniketh01 commented
In a overall, look good. I will test it out later today and will merge accordingly.

2020-04-26 13:48 UTC, Aniketh01 requested changes
There are few inline reviews still pending.

2020-04-26 13:48 UTC, Aniketh01 commented on tg_bot.py
> +        self.api = api
Change the variable name to Twitter api or something. Can be ambiguous later

2020-04-26 13:48 UTC, Aniketh01 commented on nawab.py
> +    tbot = twitter_bot.Twitter_Bot(data, dirpath)
Follow the similar naming convention as the twitter run function

2020-04-26 13:48 UTC, Aniketh01 commented on nawab.py
> +    tbot = twitter_bot.Twitter_Bot(data, dirpath)
The Twitter class objects are created twice in this file alone. See if there is a way to clean that up and have just a single instance.

2020-04-26 14:14 UTC, Aniketh01 reviewed
I think the buttons all fail now?

I also found caused error "'tuple' object has no attribute 'get_status'"

2020-04-26 15:09 UTC, merged